# This workflow will fork, do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Sync Fork and Node.js CI

on:
  push:
    branches: 
      - master

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: CSSEGISandData
          base: master
          head: master
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: true
    - uses: stefanzweifel/git-auto-commit-action@v4.1.3
      with:
        commit_message: Commiting json files generated

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event
        branch: ${{ github.head_ref }}

        # Optional git params
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        file_pattern: \*.json

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: GitHub Actions
        commit_user_email: barnalove1@gmail.com
